//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorecard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HovisDWEntities : DbContext
    {
        public HovisDWEntities()
            : base("name=HovisDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Scorecard_Details> t_Scorecard_Details { get; set; }
        public virtual DbSet<t_Scorecard_Master_Template> t_Scorecard_Master_Template { get; set; }
        public virtual DbSet<t_Scorecard_Master_Categories> t_Scorecard_Master_Categories { get; set; }
        public virtual DbSet<t_Scorecard_Minor_Categories> t_Scorecard_Minor_Categories { get; set; }
        public virtual DbSet<v_PTLStaff_MasterData_Plants> v_PTLStaff_MasterData_Plants { get; set; }
        public virtual DbSet<v_Hovis_Calendar> v_Hovis_Calendar { get; set; }
        public virtual DbSet<t_Scorecard_Master_UserSites> t_Scorecard_Master_UserSites { get; set; }
        public virtual DbSet<t_Scorecard_Target_Details_Upload> t_Scorecard_Target_Details_Upload { get; set; }
    }
}
