//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorecard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Scorecard_Master_Categories
    {
        public t_Scorecard_Master_Categories()
        {
            this.t_Scorecard_Master_Template = new HashSet<t_Scorecard_Master_Template>();
            this.t_Scorecard_Details = new HashSet<t_Scorecard_Details>();
        }
    
        public int ID { get; set; }
        public string MasterCatCode { get; set; }
    
        public virtual ICollection<t_Scorecard_Master_Template> t_Scorecard_Master_Template { get; set; }
        public virtual ICollection<t_Scorecard_Details> t_Scorecard_Details { get; set; }
    }
}
