//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorecard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Scorecard_Details
    {
        public long Recid { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
        public string SiteCode { get; set; }
        public Nullable<int> MasterCatID { get; set; }
        public Nullable<int> MinorCatID { get; set; }
        public Nullable<double> Actual { get; set; }
        public Nullable<double> Target { get; set; }
        public string Comments { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string Confirmed { get; set; }
    
        public virtual t_Scorecard_Master_Categories t_Scorecard_Master_Categories { get; set; }
        public virtual t_Scorecard_Minor_Categories t_Scorecard_Minor_Categories { get; set; }
    }
}
